name: playground
author: ""
clients:
  player:
    default: true
    runtime: browser
  thing:
    runtime: node
  autoplay-controller:
    runtime: browser
  soloist-controller:
    runtime: browser
  trigger-controller:
    runtime: browser
  granular-controller:
    runtime: browser
  soundbank-manager:
    runtime: browser
  controller:
    runtime: browser
  instructions-viewer:
    runtime: browser
  midi-learn:
    runtime: browser
