name: playground
author: ""
clients:
  player:
    default: true
    runtime: browser
  thing:
    runtime: node
  autoplay-controller:
    runtime: browser
  soloist-controller:
    runtime: browser
  trigger-controller:
    runtime: browser
